sage_example.py
=> eliminated unnecessary comments from sage_example.py

groebner/Macaulay.py, groebner/root_finder.py
=> Optimizations

groebner/Macaulay.py, groebner/TelenVanBarel.py, groebner/polynomial.py, groebner/root_finder.py, groebner/utils.py, tests/test_gsolve.py, tests/test_macaulay.py, tests/test_rootfinder.py, tests/test_tvb.py, tests/test_utils.py
Fix QR reduction errors in TVB, adds some test cases although more are needed, and implements faster zero checking. TVB still doesn't work for some cases, if it gives a KeyError in the rootFinder that means the highest degree monomial part wasn't full rank. Not sure how to fix this. It should work for dense polynomials.
=> Telen van barel

tests/test_macaulay.py, tests/test_tvb.py
Adds tests cases for Macaulay and TelenVanBarel root calculation that runs through 10 scenarios of each, 5 in MultiPower and 5 in MultiCheb in up to 4 dimensions.
=> Test cases

groebner/Macaulay.py, groebner/TelenVanBarel.py, groebner/root_finder.py, groebner/utils.py, tests/test_rootfinder.py
Uses np tricks to close #46 and close #44. Specifically makes use of fancy indexing so that pulling specific terms out of matrices is now down very quickly.
=> Speed and Memory improvement, plus a few docstrings.

groebner/Macaulay.py, groebner/TelenVanBarel.py, groebner/gsolve.py, groebner/utils.py
=> Change fullRank name to row_linear_dependencies.

groebner/Macaulay.py, groebner/TelenVanBarel.py, groebner/polynomial.py, groebner/root_finder.py, groebner/utils.py, tests/test_gsolve.py, tests/test_rootfinder.py, tests/test_utils.py
Everything looks docstringed now, the last few needing it Aaron has. Import statements are cleaned up and at the beginning of root finder all the dimensions are made equal now.
=> Docstrings and cleanup

groebner/Macaulay.py, groebner/TelenVanBarel.py, groebner/polynomial.py, groebner/projective_space.py, groebner/root_finder.py, groebner/utils.py, tests/test_tvb.py
This is all the code on my computer, new fast power basis matrix creation and a projective space folder.
=> Tvb sparse

CHEBYSHEV/DEMO.ipynb, CHEBYSHEV/TVB_Method/TVB.py, CHEBYSHEV/TVB_Method/cheb_class.py, CHEBYSHEV/TVB_Method/cheb_utils.py, CHEBYSHEV/TVB_Method/root_finder.py
Some changes I had made previously in the non-chebyshev code before, and removing the code to solve for roots in non-TVB methods.
=> removing unneeded code

tests/test_subdivision.py
This is a work in progress.
The code only passes the first test currently, so this may mean we need better tests or better code. The first test has multidimensional polynomials on [-1,1]X[-1,1]X... and the second test has 1d polynomials on [-1,1]. The third test has multidimensional polynomials on [-2,2]X[-2,2]X... and the fourth test has 1d polynomials on [-2,2].
=> Subdivision tests

numalgsolve/polynomial.py, tests/test_cheb.py, tests/test_power.py
The main change is adding the evaluate_grid function to MultiCheb.
I also did minor refactoring in polynomial.py and added tests cases for the MultiCheb.evaluate_grid method.
=> Fast poly evaluation

numalgsolve/Division.py, numalgsolve/Multiplication.py, numalgsolve/OneDimension.py, numalgsolve/TVBCore.py, numalgsolve/_stability.py, numalgsolve/_timing.py, numalgsolve/polynomial.py, numalgsolve/subdivision.py, tests/test_OneDimension.py, tests/test_cheb.py, tests/test_convert.py, tests/test_polyroots.py, tests/test_power.py, tests/test_subdivision.py, tests/test_utils.py
MAJOR UPDATE
Includes
-the bug fix found by Suzanna when parts of the Macauley matrix were zeroed out
-modified multivariate solvers to avoid using eigenvalues at all, also by Suzanna
-refactoring of subdivision plus new subdivision tests (I put this together a while ago)
-stability and timing files, making it easy to check our codes performance and graph it
-modified OneDimension to also use eigenvectors, plus new tests
-include seed before any random tests, so all testing is now deterministic
=> Suzanna bug fix

numalgsolve/Multiplication.py, numalgsolve/_stability.py, numalgsolve/_timing.py, numalgsolve/polyroots.py
Minor Update + bug fix
Finished including bertini into the timing tests.
Also fixed bug with higher dimensions when using multiplication rotated.
=> Bertini additions

Opening_matplot_files.py, numalgsolve/MacaulayReduce.py, numalgsolve/Multiplication.py, numalgsolve/ProjectiveSpace.py, numalgsolve/TVBMethod.py, numalgsolve/utils.py, requirements.txt, requirements_dev.txt, tests/test_ProjectiveSpace.py, tests/test_TVBMethod.py
TVB method is coded up in order to time against the BYU method. Preliminary version of code for identifying if there are common roots in projective space.
=> TVB timings

numalgsolve/Division.py, numalgsolve/MacaulayReduce.py, numalgsolve/subdivision.py
This fixes subdivision so it works now (at least as well as it ever did, still quite unstable at times).
=> New subdivision

numalgsolve/_stability.py
In addition to adding the residuals calculation, I rewrote a lot of the stability file to make it more manageable for future changes. Currently the graph option is broken, but I think that using the max residual numbers will be better for comparison, but we may also want to try average residuals too.
How to run
I will provide a more detailed explanation on the slack channel, but this will run it:
python _stability.py -W --coeff -n15 --dim 2
=> Better testing

numalgsolve/OneDimension.py, numalgsolve/subdivision.py, tests/test_subdivision.py, tests/test_zero_checks.py
All complete test cases now work!
The subdivision with transform cases work because we chose large tolerances.
Added the chebyshev_block_copy function which helps avoid evaluating the functions at the same point multiple times.
Added the linear case to all 1D polynomial solvers.
=> fix linear 1D, add chebyshev interpolation speedup

tests/test_LinearProjection.py, tests/test_OneDimension.py, yroots/Division.py, yroots/IntervalChecks.py, yroots/LinearProjection.py, yroots/Multiplication.py, yroots/OneDimension.py, yroots/subdivision.py
I wrote the remove_linear function to reduce the dimensionality of a system until there are no more linear equations. Now multiplication and division can handle systems with linear polynomials. Subdivision requires more thought, so I have not modified it to make use of this change.
=> added remove_linear and testing

yroots/Multiplication.py
Some issues with randomness were cropping up with creating a random polynomial for the multiplication matrix. Reimplementing the normalized random polynomial seems to fix these issues.
=> Reimplemented the normalized random polynomial.

yroots/Division.py, yroots/IntervalChecks.py, yroots/MacaulayReduce.py, yroots/Multiplication.py, yroots/NewDivision.py, yroots/RootTracker.py, yroots/subdivision.py, yroots/utils.py
hackathon edits
the biggest errors/changes we made were in trim_coeffs, where we incremented a couple of errors
=> HACKATHOOOOON

yroots/Multiplication.py
Fixed everything so our hackathon work passes Travis, and our edits work well!
=> Fixed yet another keyword/default argument problem.

tests/test_LinearProjection.py, tests/test_polyroots.py, tests/test_subdivision.py, yroots/Division.py, yroots/IntervalChecks.py, yroots/LinearProjection.py, yroots/MacaulayReduce.py, yroots/Multiplication.py, yroots/NewDivision.py, yroots/OneDimension.py, yroots/RootTracker.py, yroots/polyroots.py, yroots/subdivision.py, yroots/utils.py
So I wrote a bunch of code. I actually commented my code this time but I made a fair number of changes, so I'll give an overview. Nothing changed in the actual algorithm (besides the polishing option).
- I added a new RootTracker class. This works similar to the IntervalChecker class in that it is passed into the subdivision_solve_nd function and then stores data about the roots that are found. So for each root it stores the interval it was found in and the method used to find it. I figure it might also be useful to store things like the approximation errors on the approximated polynomials or other stats.
- I changed the tolerances. They are now stored in a Tolerances class that is passed into subdivision_solve_nd. Part of the motivation for this is that it makes the recursive calls of …
=> fix the tolerances, add polishing

Optimal_QR.py, yroots/RootTracker.py, yroots/subdivision.py
- Resolved an error within RootTracker.keepPotentialRoots where cond wasn't being passed in
- Resolved an error in the base case of subdivision.py where 'zeros' was called before
assignment (simple fix of changing 'zeros' to 'zero'.
- Added in the commented out tests for the Optimal QR script.
- Added a safety net pickle object that saves the dictionary after each method has run through
all the tests.
=> Fixed problems with testing on some Chebfun tests.

tol_grid_search.py, yroots/MacaulayReduce.py, yroots/Multiplication.py, yroots/RootTracker.py, yroots/subdivision.py
I added a parameter that allows us to specify the target degree (the degree to which we subdivide before we commit to building the Macaulay matrices).
Additionally, I fixed a few bugs that showed up with running the TVB method, and another issue in the RootTracker class that caused our Optimal_QR script to run into trouble on Chebfun test 7.4.
Other than that, there were some minor formatting changes that I made that don't affect the functionality of the code.
=> Target Degree + Bug fixes

tests/test_polyroots.py, yroots/Multiplication.py, yroots/subdivision.py, yroots/utils.py
Polyroots now works correctly on a linear system of polynomials.
=> Polyroots for Linear Systems Fix

tests/test_zero_checks.py, yroots/IntervalChecks.py, yroots/old_code/OldIntervalChecks.py
1. Moved the unused checks to yroots/old_code/OldIntervalChecks.py. 
2. Fixed a small bug in quadratic_check_nd that had to do with ensuring the critical points were actually within the correct interval. 
3. Changed how we compare the extrema to the sum of the other coefficients in all three quadratic_checks to make it slightly faster.
=> Cleaning up Interval Checks

tests/test_zero_checks.py, yroots/IntervalChecks.py, yroots/old_code/OldIntervalChecks.py
Speed-ups in the quadratic checks
=> Sue develop2

yroots/subdivision.py
*added a try/catch to expand the initialized values array for the chebyshev block copy when necessary. Will become obsolete if we force the approximation degree to be nonincreasing. This required changing from memoize to Memoize to allow us to access the cache
*check for type of function list differently. I changed this because it assumed the problem was one dimensional when I passed in an array of functions instead of a list of functions
* Remnants of old code removed: sign change, and the double definition of "slices" in interval_approx_nd
=> Expanding values array

yroots/subdivision.py
- Fixed a bug so good_degs no longer goes above the inital approximation degree.
- Fixed a bug so target_deg more accurately reflects the target degree and not the
coefficient tensor shape.
=> Adjusted good_degs and fixed a bug with target_deg

yroots/subdivision.py
Added an interval buffer that helps us to find roots that are along the borders of our search region. Also, set a fixed max recursion depth at 52.
=> Interval Buffer + Fixed Max Recursion Depth

yroots/subdivision.py
Function reordering option A was added into subdivision_solve_nd
=> Added function reordering

yroots/subdivision.py
make target degree be one (for linear)
get rid of double counting doubling size of array for cheby approx
make degree variable actually be the degree (IE subtract one to not count constant term and get actual degree)
=> fixes to target degree and other degree variables

yroots/IntervalChecks.py
The progress bar was double counting interval area when calling track_interval_bounded.
=> Fixed progress bar tracking error

yroots/ChebyshevSubdivisionSolver.py, yroots/Combined_Solver.py, yroots/M_maker.py, yroots/cond_numbers.py, yroots/test_Combined_Solver.py
This new solver is aware of the fact that the ChebyshevSubdivisionSolver solves on the [-1,1]^n interval. It transforms the roots found on that standard interval into the interval of interest.
=> Add new Combined_Solver to codebase

approx_class_2.py, test_approximation_class.py, test_mine_w_eriks.py, tests/Combined_Solver, tests/test_mine_w_eriks.py, yroots/ChebyshevSubdivisionSolverWCTC.py, yroots/Combined_Solver, yroots/Combined_Solver.py, yroots/Constant_Term_Test.py, yroots/M_maker.py, yroots/approx_class_2.py, yroots/ec2_instance_thing.sh, yroots/eriks_code.py, yroots/sub_sam.py, yroots/test_Combined_Solver.py, yroots/test_tracked_interval_ii.py
Updating `combined_solver.py` to allow for `exact` option.
=> Erik subdivision solver updates

yroots/ChebyshevSubdivisionSolver.py, yroots/Combined_Solver.py, yroots/QuadraticCheck.py
Created a new file called QuadraticCheck.py. Works similar to the old quadratic term check in the interval checks file, but slight changes needed to be made in order for it to be compatible with new code. Now it goes through each subinterval one by one and loops through each of the functions, and if one of them is guaranteed not to have a root in the interval according to the quadratic term check, it throws the interval out.
Also added three new parameters to the solve function in Combined_Solver.py: constant_check, low_dim_quadratic_check, and all_dim_quadratic_check. The first runs the constant check after every subdivision if set to true, the second runs the quadratic check after every subdivision if set to true for dimensions 3 and lower, the third runs the quadratic check after every …
=> Pushed code for quadratic term check

yroots/ChebyshevSubdivisionSolver.py, yroots/QuadraticCheck.py
Oversight that caused quadratic and constant term checks not to run has been fixed. Also fixed return statement in quadratic check nd that caused tests to fail.
=> Fixed issues with constant and quadratic checks.

yroots/ChebyshevSubdivisionSolver.py, yroots/Combined_Solver.py
In the Combined_Solver file the modules are now imported from yroots instead of being imported directly so when someone tries to import from yroots these modules will be imported correctly as well. Also inserted a missing comma in line 1338 of ChebyshevSubdivisionSolver.
=> Fixed some errors associated with importing module

yroots/Combined_Solver.py, yroots/M_maker.py
This is so the user can tweak the capping degree of the approximation.
=> allow option to increase (or decrease) max_deg

yroots/M_maker.py
from 16 --> 64, now passing all edge cases with quick runtime
=> increasing max_deg in dim 4

yroots/Combined_Solver.py
For the func boundary issue, added cases for whether a list of different bounds are inputted or just integer/float bounds.
For the fixing degree guesser bug, solved the issue by adding a special case if the source of the function is the call to solve itself rather than a separately defined function.
=> Fixing Degree Guesser Bug, solve func boundary input issue

yroots/Combined_Solver.py, yroots/M_maker.py
This pull request primarily contains the following changes:
- Adding/improving documentation for the M_maker.py and Combined_Solver.py files
- Adding a FFT dictionary to look up already computed FFT values when creating Chebyshev approximations
- Changing max_deg to 32 for dimension 4
=> Documentation, FFT Dictionary, Max_Deg[dim=4] Update

yroots/M_maker.py
Using this code, the solver can use approximations of varying degrees in different dimensions, in some cases significantly speeding up runtime!
=> Implemented nonsquare approximation

chebfun2_suite.py, yroots/ChebyshevApproximator.py, yroots/ChebyshevSubdivisionSolver.py
Implements constant check in the approximator, sets trimMs to lower bound to decrease error, and edits chebfun2_suite.py so that we pass all of our tests
=> Some final updates

yroots/ChebyshevApproximator.py, yroots/ChebyshevSubdivisionSolver.py, yroots/Combined_Solver.py, yroots/polynomial.py
Changes include the following, while there may be some that I forgot:
- Cleaned out polynomial.py to remove functionality not needed for rootfinding with our solver
- Improved documentation/comments
- Improved approximator to skip past variables not used in the function
- Added verbose setting to solver that tracks progress as well as warnings if things go awry
=> Several changes over the past few weeks

README.md, chebfun2_suite.py, docs/index.html
Updating norm test tolerance for chebfun problem 4.2 from the most recent pull request from Erik and also updating the code requirements listed in our readme (the version of python, pip, etc. needed to run our code)
=> Updating chebfun 4.2 tolerance + readme update

docs/index.html
Added the demo notebook links to readme + documentation website.
=> Adding demo notebook links to readme + doc site

README.md, setup.py, yroots/ChebyshevApproximator.py, yroots/ChebyshevSubdivisionSolver.py, yroots/Combined_Solver.py
Changing setup.py so that it installs the yroots package instead of the RootFinding one.
Updating the installation instructions in the readme
=> Updating setup.py + installation instructions

yroots/ChebyshevSubdivisionSolver.py
Patches bug that would throw out all dimensions as subdivision candidates.
=> always subdivide in some dimension
